name: Deploy to VPS

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_KNOWN_HOSTS:
        required: true
      VPS_USER:
        required: true
      VPS_HOST:
        required: true
      DATABASE_URL:
        required: true
      TEST_DATABASE_URL:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Identify deleted files
        id: deleted_files
        run: |
          echo "::set-output name=files::$(git diff --name-status ${{ github.event.before }} ${{ github.sha }} | grep '^D' | cut -f2)"

      - name: Set up SSH agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Debug SSH connection
        run: |
          echo "Attempting to connect to ${{ secrets.VPS_HOST }}"
          ssh -vvv -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo 'SSH connection successful'"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Set up SSH known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          for i in {1..5}; do
            if ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts; then
              break
            fi
            echo "Retry $i: Waiting for host resolution..."
            sleep 10
          done

      - name: Set deployment path and environment
        id: deploy_info
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=path::/home/recipescheduler_host/www/recipescheduler-prod"
            echo "::set-output name=env::prod"
          else
            echo "::set-output name=path::/home/recipescheduler_host/www/recipescheduler-test"
            echo "::set-output name=env::test"
          fi

      - name: Delete removed files on server
        run: |
          for file in ${{ steps.deleted_files.outputs.files }}; do
            ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "rm -f ${{ steps.deploy_path.outputs.path }}/${GITHUB_REPOSITORY#*/}/$file"
          done
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Prepare deployment directory
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            mkdir -p ${{ steps.deploy_path.outputs.path }}/${GITHUB_REPOSITORY#*/}
            chmod 755 ${{ steps.deploy_path.outputs.path }}/${GITHUB_REPOSITORY#*/}
          "
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          
      - name: Sync files to the server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30" ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ steps.deploy_path.outputs.path }}/${GITHUB_REPOSITORY#*/}/
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Set permissions
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            chown -R www-data:www-data ${{ steps.deploy_path.outputs.path }}/${GITHUB_REPOSITORY#*/}
            chmod -R 755 ${{ steps.deploy_path.outputs.path }}/${GITHUB_REPOSITORY#*/}
            find ${{ steps.deploy_path.outputs.path }}/${GITHUB_REPOSITORY#*/} -type f -exec chmod 644 {} \;
          "
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Post-deployment tasks (Backend)
        if: endsWith(github.repository, 'BackEnd')
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd ${{ steps.deploy_info.outputs.path }}/backend
            echo 'Current directory: '\$(pwd)
            echo 'Directory contents:'
            ls -la
            source venv/bin/activate
            echo 'Python version: '\$(python --version 2>&1)
            echo 'Pip version: '\$(pip --version 2>&1)
            pip install -r requirements.txt
            alembic upgrade head
            sudo systemctl restart recipescheduler@${{ steps.deploy_info.outputs.env }}.service || echo 'Failed to restart service'
            echo 'Service status:'
            sudo systemctl status recipescheduler@${{ steps.deploy_info.outputs.env }}.service
          "
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Post-deployment tasks (Frontend)
        if: endsWith(github.repository, 'FrontEnd')
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd ${{ steps.deploy_info.outputs.path }}/frontend
            echo 'Current directory: '\$(pwd)
            echo 'Directory contents:'
            ls -la
            npm install
            npm run build
            sudo systemctl restart apache2 || echo 'Failed to restart Apache2'
          "
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
